In [25]:
import numpy as np
from scipy.io import loadmat
!pip install open3d-python
import open3d

    100% |████████████████████████████████| 3.3MB 493kB/s eta 0:00:01
You are using pip version 9.0.1, however version 19.0.3 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.


In [23]:
source = loadmat("Data/source.mat")
target = loadmat("Data/target.mat")
source['source'].shape
target['target'].shape
np.genfromtxt("Data/data/0000000000.pcd", delimiter='', skip_header=11) 

array([[-7.0906661e-02, -8.5087997e-01,  2.6589999e+00,  1.5581775e-38],
       [-6.0319997e-02, -8.4447998e-01,  2.6389999e+00,  1.4844215e-38],
       [-5.0266664e-02, -8.4447998e-01,  2.6389999e+00,  1.2354580e-38],
       ...,
       [ 1.1858714e+01,  2.7836773e+01,  6.5535004e+01,  1.9437768e-38],
       [ 1.4355287e+01,  2.7836773e+01,  6.5535004e+01,  1.1787704e-38],
       [ 1.4854601e+01,  2.7836773e+01,  6.5535004e+01,  1.4834109e-38]])

In [28]:
print("Load a ply point cloud, print it, and render it")
pcd = open3d.read_point_cloud("Data/data/0000000000.pcd")
print(pcd)
print(np.asarray(pcd.points))
open3d.draw_geometries([pcd])

Load a ply point cloud, print it, and render it
geometry::PointCloud with 68742 points.
[[-7.0906661e-02 -8.5087997e-01  2.6589999e+00]
 [-6.0319997e-02 -8.4447998e-01  2.6389999e+00]
 [-5.0266664e-02 -8.4447998e-01  2.6389999e+00]
 ...
 [ 1.1858714e+01  2.7836773e+01  6.5535004e+01]
 [ 1.4355287e+01  2.7836773e+01  6.5535004e+01]
 [ 1.4854601e+01  2.7836773e+01  6.5535004e+01]]


In [31]:
R = np.eye(10)
t = 0